### ISSUE TITLE
Unable to generate lightcones, 21cmFast exists with disk quota exceeded error

### ISSUE THREAD

**Issue by j-c-carr** [j-c-carr/lightcones#20]
```
Due to MODULEPATH changes, the following have been reloaded:
  1) libfabric/1.10.1     2) openmpi/4.0.3     3) ucx/1.8.0

Lightcone 0 done.
Lightcone 1 done.
Lightcone 2 done.
Lightcone 3 done.
Lightcone 4 done.
Lightcone 5 done.
Lightcone 6 done.
Lightcone 7 done.
Lightcone 8 done.
Lightcone 9 done.
2021-07-24 17:49:35,960 | WARNING | _utils.py::write() | When attempting to write BrightnessTemp to file, write failed with the following error. Continuing without caching.
When attempting to write BrightnessTemp to file, write failed with the following error. Continuing without caching.
2021-07-24 17:49:35,960 | WARNING | _utils.py::write() | Unable to create file (file write failed: time = Sat Jul 24 17:49:35 2021
, filename = '/home/jccarr/21cmFAST-cache/BrightnessTemp_16be42dae6206c73abe9653cef661fcd_r706.h5', file descriptor = 8, errno = 122, error message = 'Disk quota exceeded', buf = 0x19fe888, total write size = 96, bytes this sub-write = 96, bytes actually written = 18446744073709551615, offset = 0)
Unable to create file (file write failed: time = Sat Jul 24 17:49:35 2021
, filename = '/home/jccarr/21cmFAST-cache/BrightnessTemp_16be42dae6206c73abe9653cef661fcd_r706.h5', file descriptor = 8, errno = 122, error message = 'Disk quota exceeded', buf = 0x19fe888, total write size = 96, bytes this sub-write = 96, bytes actually written = 18446744073709551615, offset = 0)
Traceback (most recent call last):
  File "/home/jccarr/.env/lib/python3.7/site-packages/py21cmfast/_utils.py", line 707, in write
    boxes.create_dataset(k, data=getattr(self, k))
  File "/home/jccarr/.env/lib/python3.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/jccarr/.env/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 170, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 222, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 132, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite
OSError: Can't write data (file write failed: time = Sat Jul 24 17:49:36 2021
, filename = '/home/jccarr/21cmFAST-cache/PerturbedField_13f67b43a9e1de86d2250038adfb319b_r706.h5', file descriptor = 8, errno = 122, error message = 'Disk quota exceeded', buf = 0x8d06ff0, total write size = 8386720, bytes this sub-write = 8386720, bytes actually written = 18446744073709551615, offset = 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jccarr/lightcones/data-generation/bin/main.py", line 282, in <module>
    make_cones(all_params, args)
  File "/home/jccarr/lightcones/data-generation/bin/main.py", line 173, in make_cones
    lightcones, redshifts = LM.generate_lightcones()
  File "/home/jccarr/lightcones/data-generation/bin/lightcone_manager.py", line 150, in generate_lightcones
    random_seed = seed[i],
  File "/home/jccarr/.env/lib/python3.7/site-packages/py21cmfast/wrapper.py", line 2653, in run_lightcone
    write=write,
  File "/home/jccarr/.env/lib/python3.7/site-packages/py21cmfast/wrapper.py", line 984, in perturb_field
    write=write,
  File "/home/jccarr/.env/lib/python3.7/site-packages/py21cmfast/_utils.py", line 947, in compute
    self.write(direc)
  File "/home/jccarr/.env/lib/python3.7/site-packages/py21cmfast/_utils.py", line 710, in write
    boxes.attrs[k] = getattr(self, k)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/jccarr/.env/lib/python3.7/site-packages/h5py/_hl/files.py", line 461, in __exit__
    self.close()
  File "/home/jccarr/.env/lib/python3.7/site-packages/h5py/_hl/files.py", line 443, in close
    h5i.dec_ref(id_)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5i.pyx", line 150, in h5py.h5i.dec_ref
RuntimeError: Problems closing file (file write failed: time = Sat Jul 24 17:49:36 2021
, filename = '/home/jccarr/21cmFAST-cache/PerturbedField_13f67b43a9e1de86d2250038adfb319b_r706.h5', file descriptor = 8, errno = 122, error message = 'Disk quota exceeded', buf = 0x34cce00, total write size = 4096, bytes this sub-write = 4096, bytes actually written = 18446744073709551615, offset = 0)
./data_generator.sh: line 24: 188431 Segmentation fault      (core dumped) python3 /home/jccarr/lightcones/data-generation/bin/main.py $title lightcones/data-generation/in/config_z7-9.yml --make_cones
```

**Comment by j-c-carr** [comment]
Lightcones were being generated in the home folder instead of the scratch folder. I just had add the `direc` parameter when running the lightcone simulations.
