### ISSUE TITLE
call to stats() in line 224 of isensee_train.py produces IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by j-c-carr** [j-c-carr/lightcones#3]
Trace: 
```
Traceback (most recent call last):
  File "bin/isensee_train.py", line 221, in <module>
    stats(y_valid, preds_val_t, X_valid, FIG_DIR)
  File "/home/jcc/Documents/cosmology/lightcones/reproducing-results/bin/plot.py", line 249, in stats
    map_array = res_frac(y_valid, y_pred)
  File "/home/jcc/Documents/cosmology/lightcones/reproducing-results/bin/plot.py", line 190, in res_frac
    res_frac_cubes = [y_valid[i,:,:,:,0] - y_pred[i,:,:,:,0] for i in range(y_valid.shape[0])]
  File "/home/jcc/Documents/cosmology/lightcones/reproducing-results/bin/plot.py", line 190, in <listcomp>
    res_frac_cubes = [y_valid[i,:,:,:,0] - y_pred[i,:,:,:,0] for i in range(y_valid.shape[0])]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by j-c-carr** [comment]
The error is from the call to `res_frac` in the `plot.py` file. It looks like this is caused by a mismatch between `y_valid.shape` and `y_pred.shape`. Inside the `res_frac` function, 
```
(Pdb) p y_valid.shape
(2, 128, 128, 128, 1)
(Pdb) p y_pred.shape
(1, 128, 128, 128, 1)
```
Not sure if this is from the way they are reshaped or if the model produces the `y_pred` arrays in a different shape (in this case, the problem might be due to reshaping the weights)

**Comment by j-c-carr** [comment]
This was due to the fact that I was testing the code with three training samples, which caused a size mismatch between `y_valid.shape` and `y_train.shape`. Importantly, they are expected to be the same size, since we are using a test split of 0.5. During training.
