### ISSUE TITLE
Call to res_stats() in line 229 of plot.py produces ZeroDivisionError

### ISSUE THREAD

**Issue by j-c-carr** [j-c-carr/lightcones#4]
Full traceback:
```
Traceback (most recent call last):
  File "bin/isensee_train.py", line 229, in <module>
    stats(y_valid, preds_val_t, X_valid, FIG_DIR)
  File "/home/jcc/Documents/cosmology/lightcones/reproducing-results/bin/plot.py", line 281, in stats
    precision, recall, accuracy, F1 = res_stats(y_valid, y_pred)
  File "/home/jcc/Documents/cosmology/lightcones/reproducing-results/bin/plot.py", line 229, in res_stats
    recall = [TP[i]/(TP[i] + FN[i]) for i in range(len(TP))]
  File "/home/jcc/Documents/cosmology/lightcones/reproducing-results/bin/plot.py", line 229, in <listcomp>
    recall = [TP[i]/(TP[i] + FN[i]) for i in range(len(TP))]
ZeroDivisionError: division by zero
```

**Comment by j-c-carr** [comment]
I think this is caused by the small sample size (again only using two images for `y_train` and two for `y_pred`. Basically the code finds all (true|false) (positives|negatives) and adds them together, and then uses this to calculate precision, accuracy, and recall. In the `res_stats()` function, the variables are 
```
TP = [0, 0]
FN = [0, 0]
TN = [29645, 49044]
FP = [146133, 315293]
```
So when calculating recall there is a division by zero error since in the denominator we have TP + FN. I added a try/catch block to resolve this, but it seems strange that there would be no TP or FN, so there might be something wrong elsewhere. For now, the `ZeroDivisionError` goes away so I will close this for now.

**Comment by j-c-carr** [comment]
Spoke to Sam about this, it is weird that there are no true positives in this particular box, I will try to print a slice of the box to see what it looks like

**Comment by j-c-carr** [comment]
Handling the ZeroDivisionErrors by throwing everything in a try/except block is a workaround solution for now, if the problem persists when I run the full training set then I will have to figure out another solution.
